services:
  redis-compose:
    image: redis
    container_name: local-redis
    ports:
      - "6379:6379"
  mongo-compose:
    image: mongo
    container_name: local-mongo
    ports:
      - "27017:27017"
