//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comrade.Core.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BusinessMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BusinessMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Comrade.Core.Messages.BusinessMessage", typeof(BusinessMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não atingiu o número minimo de caracteres..
        /// </summary>
        public static string LKUP2001 {
            get {
                return ResourceManager.GetString("LKUP2001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro Incluído com Success!.
        /// </summary>
        public static string MSG01 {
            get {
                return ResourceManager.GetString("MSG01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro Alterado com Success!.
        /// </summary>
        public static string MSG02 {
            get {
                return ResourceManager.GetString("MSG02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro Excluído com Success!.
        /// </summary>
        public static string MSG03 {
            get {
                return ResourceManager.GetString("MSG03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro não Existe!.
        /// </summary>
        public static string MSG04 {
            get {
                return ResourceManager.GetString("MSG04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum registro encontrado..
        /// </summary>
        public static string MSG05 {
            get {
                return ResourceManager.GetString("MSG05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro já exists para a Unidade, Data e Hora informados. Registro não foi salvo..
        /// </summary>
        public static string MSG06 {
            get {
                return ResourceManager.GetString("MSG06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao tentar salvar o registro no banco de dados, caso o problema persista, por favor entrar em contato com o suporte..
        /// </summary>
        public static string MSG07 {
            get {
                return ResourceManager.GetString("MSG07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro já exists com mesmo code, por favor informe outro code..
        /// </summary>
        public static string MSG08 {
            get {
                return ResourceManager.GetString("MSG08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code do cargo invalido..
        /// </summary>
        public static string MSG09 {
            get {
                return ResourceManager.GetString("MSG09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um menu cadastrado com esse nome..
        /// </summary>
        public static string MSG20 {
            get {
                return ResourceManager.GetString("MSG20", resourceCulture);
            }
        }
    }
}
