using Comrade.Application.Components.SystemUserSystemRoleComponent.Contracts;

namespace Comrade.Application.Components.SystemUserSystemRoleComponent.Validations;

public class SystemUserSystemRoleEditValidation : SystemUserSystemRoleValidation<SystemUserSystemRoleEditDto>
{
}