// <auto-generated />
using System;
using Comrade.Persistence.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Comrade.Persistence.Migrations
{
    [DbContext(typeof(ComradeContext))]
    [Migration("20220912214350_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Comrade.Domain.Models.Airplane", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("airp_uuid_airplane");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("airp_tx_code");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("airp_tx_model");

                    b.Property<int>("PassengerQuantity")
                        .HasColumnType("int")
                        .HasColumnName("airp_qt_passenger");

                    b.Property<string>("RegisterDate")
                        .IsRequired()
                        .HasColumnType("varchar(48)")
                        .HasColumnName("airp_dt_register");

                    b.HasKey("Id")
                        .HasName("pk_airp_airplane");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_un_airp_tx_code");

                    b.ToTable("airp_airplane");
                });

            modelBuilder.Entity("Comrade.Domain.Models.SystemMenu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("syme_uuid_system_menu");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("syme_tx_description");

                    b.Property<Guid?>("FatherId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("syme_uuid_father");

                    b.Property<string>("Route")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("syme_tx_route");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("syme_tx_text");

                    b.HasKey("Id")
                        .HasName("pk_syme_system_menu");

                    b.HasIndex("FatherId");

                    b.ToTable("syme_system_menu");
                });

            modelBuilder.Entity("Comrade.Domain.Models.SystemPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("sype_uuid_system_permission");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("sype_tx_name");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("sype_tx_tag");

                    b.HasKey("Id")
                        .HasName("pk_sype_system_permission");

                    b.ToTable("sype_system_permission");
                });

            modelBuilder.Entity("Comrade.Domain.Models.SystemRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("syro_uuid_system_role");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("syro_tx_name");

                    b.HasKey("Id")
                        .HasName("pk_syro_system_role");

                    b.ToTable("syro_system_role");
                });

            modelBuilder.Entity("Comrade.Domain.Models.SystemUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("syus_uuid_system_user");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("syus_tx_email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("syus_tx_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(1023)
                        .HasColumnType("varchar(1023)")
                        .HasColumnName("syus_pw_password");

                    b.Property<string>("RegisterDate")
                        .HasColumnType("varchar(48)")
                        .HasColumnName("syus_dt_register");

                    b.Property<string>("Registration")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("syus_tx_registration");

                    b.HasKey("Id")
                        .HasName("pk_syus_system_user");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_un_syus_tx_email")
                        .HasFilter("[syus_tx_email] IS NOT NULL");

                    b.HasIndex("Registration")
                        .IsUnique()
                        .HasDatabaseName("ix_un_syus_tx_registration");

                    b.ToTable("syus_system_user");
                });

            modelBuilder.Entity("SystemPermissionSystemRole", b =>
                {
                    b.Property<Guid>("SystemPermissionsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SystemRolesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SystemPermissionsId", "SystemRolesId");

                    b.HasIndex("SystemRolesId");

                    b.ToTable("syro_system_role_sype_system_permission", (string)null);
                });

            modelBuilder.Entity("SystemPermissionSystemUser", b =>
                {
                    b.Property<Guid>("SystemPermissionsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SystemUsersId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SystemPermissionsId", "SystemUsersId");

                    b.HasIndex("SystemUsersId");

                    b.ToTable("syus_system_user_sype_system_permission", (string)null);
                });

            modelBuilder.Entity("SystemRoleSystemUser", b =>
                {
                    b.Property<Guid>("SystemRolesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SystemUsersId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SystemRolesId", "SystemUsersId");

                    b.HasIndex("SystemUsersId");

                    b.ToTable("syus_system_user_syro_system_role", (string)null);
                });

            modelBuilder.Entity("Comrade.Domain.Models.SystemMenu", b =>
                {
                    b.HasOne("Comrade.Domain.Models.SystemMenu", "Father")
                        .WithMany("Childrens")
                        .HasForeignKey("FatherId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Father");
                });

            modelBuilder.Entity("SystemPermissionSystemRole", b =>
                {
                    b.HasOne("Comrade.Domain.Models.SystemPermission", null)
                        .WithMany()
                        .HasForeignKey("SystemPermissionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Comrade.Domain.Models.SystemRole", null)
                        .WithMany()
                        .HasForeignKey("SystemRolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SystemPermissionSystemUser", b =>
                {
                    b.HasOne("Comrade.Domain.Models.SystemPermission", null)
                        .WithMany()
                        .HasForeignKey("SystemPermissionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Comrade.Domain.Models.SystemUser", null)
                        .WithMany()
                        .HasForeignKey("SystemUsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SystemRoleSystemUser", b =>
                {
                    b.HasOne("Comrade.Domain.Models.SystemRole", null)
                        .WithMany()
                        .HasForeignKey("SystemRolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Comrade.Domain.Models.SystemUser", null)
                        .WithMany()
                        .HasForeignKey("SystemUsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Comrade.Domain.Models.SystemMenu", b =>
                {
                    b.Navigation("Childrens");
                });
#pragma warning restore 612, 618
        }
    }
}
