// <auto-generated />
using System;
using Comrade.Persistence.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Comrade.Persistence.Migrations
{
    [DbContext(typeof(ComradeContext))]
    partial class ComradeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Comrade.Domain.Models.Airplane", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("airp_uuid_airplane");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("airp_tx_code");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("airp_tx_model");

                    b.Property<int>("PassengerQuantity")
                        .HasColumnType("int")
                        .HasColumnName("airp_qt_passenger");

                    b.Property<string>("RegisterDate")
                        .IsRequired()
                        .HasColumnType("varchar(48)")
                        .HasColumnName("airp_dt_register");

                    b.HasKey("Id")
                        .HasName("pk_airp_airplane");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_un_airp_tx_code");

                    b.ToTable("airp_airplane");

                    b.HasData(
                        new
                        {
                            Id = new Guid("063f44b8-df8b-4f96-889a-75b9d67c546f"),
                            Code = "123",
                            Model = "111",
                            PassengerQuantity = 34,
                            RegisterDate = "2017-06-18 00:00:00"
                        },
                        new
                        {
                            Id = new Guid("84ceb636-bbc5-49ed-8b5f-512931f649ec"),
                            Code = "456",
                            Model = "222",
                            PassengerQuantity = 23,
                            RegisterDate = "2017-07-18 00:00:00"
                        },
                        new
                        {
                            Id = new Guid("64cf5861-0b69-41b0-9a07-060f7eeb4ad6"),
                            Code = "567",
                            Model = "333",
                            PassengerQuantity = 12,
                            RegisterDate = "2017-05-18 00:00:00"
                        });
                });

            modelBuilder.Entity("Comrade.Domain.Models.SystemMenu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("syme_uuid_system_menu");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("syme_tx_description");

                    b.Property<string>("Icon")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("syme_tx_icon");

                    b.Property<Guid?>("MenuId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("syme_uuid_menu");

                    b.Property<string>("Route")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("syme_tx_route");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("syme_tx_text");

                    b.HasKey("Id")
                        .HasName("pk_syme_system_menu");

                    b.HasIndex("MenuId");

                    b.ToTable("syme_system_menu");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6adf10d0-1b83-46f2-91eb-0c64f1c638a6"),
                            Description = "Menu 1 - Description",
                            Route = "/menu-1",
                            Text = "Menu 1"
                        },
                        new
                        {
                            Id = new Guid("6adf10d0-1b83-46f2-91eb-0c64f1c638a7"),
                            Description = "Menu 2 - Description",
                            Route = "/menu-2",
                            Text = "Menu 2"
                        },
                        new
                        {
                            Id = new Guid("6adf10d0-1b83-46f2-91eb-0c64f1c638a8"),
                            Description = "Menu 3 - Description",
                            Route = "/menu-3",
                            Text = "Menu 3"
                        },
                        new
                        {
                            Id = new Guid("6adf10d0-1b83-46f2-91eb-0c64f1c638a9"),
                            Description = "SubMenu 3.1 - Description",
                            MenuId = new Guid("6adf10d0-1b83-46f2-91eb-0c64f1c638a8"),
                            Route = "/menu-3-1",
                            Text = "SubMenu 3.1"
                        },
                        new
                        {
                            Id = new Guid("6adf10d0-1b83-46f2-91eb-0c64f1c638b1"),
                            Description = "SubMenu 3.2 - Description",
                            MenuId = new Guid("6adf10d0-1b83-46f2-91eb-0c64f1c638a8"),
                            Route = "/menu-3-2",
                            Text = "SubMenu 3.2"
                        });
                });

            modelBuilder.Entity("Comrade.Domain.Models.SystemPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("sype_uuid_system_permission");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("sype_tx_name");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("sype_tx_tag");

                    b.HasKey("Id")
                        .HasName("pk_sype_system_permission");

                    b.ToTable("sype_system_permission");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6adf10d0-1b83-46f2-91eb-0c64f1c638a1"),
                            Name = "CREATE",
                            Tag = "CREATE"
                        },
                        new
                        {
                            Id = new Guid("6adf10d0-1b83-46f2-91eb-0c64f1c638a2"),
                            Name = "READ",
                            Tag = "READ"
                        },
                        new
                        {
                            Id = new Guid("6adf10d0-1b83-46f2-91eb-0c64f1c638a3"),
                            Name = "UPDATE",
                            Tag = "UPDATE"
                        },
                        new
                        {
                            Id = new Guid("6adf10d0-1b83-46f2-91eb-0c64f1c638a4"),
                            Name = "DELETE",
                            Tag = "DELETE"
                        });
                });

            modelBuilder.Entity("Comrade.Domain.Models.SystemRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("syro_uuid_system_role");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("syro_tx_name");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("syro_tx_tag");

                    b.HasKey("Id")
                        .HasName("pk_syro_system_role");

                    b.ToTable("syro_system_role");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3fa85f64-5717-4562-b3fc-2c963f66afa6"),
                            Name = "ADM",
                            Tag = ""
                        },
                        new
                        {
                            Id = new Guid("6adf10d0-1b83-46f2-91eb-0c64f1c638a7"),
                            Name = "CREATOR",
                            Tag = ""
                        });
                });

            modelBuilder.Entity("Comrade.Domain.Models.SystemRoleSystemPermission", b =>
                {
                    b.Property<Guid>("SystemRoleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("fk_uuid_system_role");

                    b.Property<Guid>("SystemPermissionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("fk_uuid_system_permission");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("pk_uuid_syro_system_role_sype_system_permission");

                    b.HasKey("SystemRoleId", "SystemPermissionId")
                        .HasName("rl_syro_system_role_sype_system_permission");

                    b.HasIndex("SystemPermissionId");

                    b.ToTable("syro_system_role_sype_system_permission");

                    b.HasData(
                        new
                        {
                            SystemRoleId = new Guid("3fa85f64-5717-4562-b3fc-2c963f66afa6"),
                            SystemPermissionId = new Guid("6adf10d0-1b83-46f2-91eb-0c64f1c638a1"),
                            Id = new Guid("7bca96d5-374c-4baf-9004-15d78c0dcaba")
                        },
                        new
                        {
                            SystemRoleId = new Guid("3fa85f64-5717-4562-b3fc-2c963f66afa6"),
                            SystemPermissionId = new Guid("6adf10d0-1b83-46f2-91eb-0c64f1c638a2"),
                            Id = new Guid("d91a3f44-94b0-4e79-a658-49183b065f22")
                        },
                        new
                        {
                            SystemRoleId = new Guid("3fa85f64-5717-4562-b3fc-2c963f66afa6"),
                            SystemPermissionId = new Guid("6adf10d0-1b83-46f2-91eb-0c64f1c638a3"),
                            Id = new Guid("29611eda-a1e5-44b9-acad-626c541a974f")
                        },
                        new
                        {
                            SystemRoleId = new Guid("3fa85f64-5717-4562-b3fc-2c963f66afa6"),
                            SystemPermissionId = new Guid("6adf10d0-1b83-46f2-91eb-0c64f1c638a4"),
                            Id = new Guid("e92e13d3-d621-42e0-8009-f4775f016ca1")
                        },
                        new
                        {
                            SystemRoleId = new Guid("6adf10d0-1b83-46f2-91eb-0c64f1c638a7"),
                            SystemPermissionId = new Guid("6adf10d0-1b83-46f2-91eb-0c64f1c638a1"),
                            Id = new Guid("fc699c66-4d75-48e1-be68-486adb647b29")
                        },
                        new
                        {
                            SystemRoleId = new Guid("6adf10d0-1b83-46f2-91eb-0c64f1c638a7"),
                            SystemPermissionId = new Guid("6adf10d0-1b83-46f2-91eb-0c64f1c638a2"),
                            Id = new Guid("eefde252-afea-4a34-8e8f-114ac2338ee4")
                        },
                        new
                        {
                            SystemRoleId = new Guid("6adf10d0-1b83-46f2-91eb-0c64f1c638a7"),
                            SystemPermissionId = new Guid("6adf10d0-1b83-46f2-91eb-0c64f1c638a3"),
                            Id = new Guid("d0190452-0eb9-435d-bc00-a5b93fdc4a99")
                        });
                });

            modelBuilder.Entity("Comrade.Domain.Models.SystemUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("syus_uuid_system_user");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("syus_tx_email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("syus_tx_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(1023)
                        .HasColumnType("varchar(1023)")
                        .HasColumnName("syus_pw_password");

                    b.Property<string>("RegisterDate")
                        .HasColumnType("varchar(48)")
                        .HasColumnName("syus_dt_register");

                    b.Property<string>("Registration")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("syus_tx_registration");

                    b.HasKey("Id")
                        .HasName("pk_syus_system_user");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_un_syus_tx_email")
                        .HasFilter("[syus_tx_email] IS NOT NULL");

                    b.HasIndex("Registration")
                        .IsUnique()
                        .HasDatabaseName("ix_un_syus_tx_registration");

                    b.ToTable("syus_system_user");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6adf10d0-1b83-46f2-91eb-0c64f1c638a5"),
                            Email = "777@testObject",
                            Name = "aaaa",
                            Password = "100.SdwfwU4tDWbBkLlBNd7Vcg==.cGEYFjBRNpLrCxzYNIbSdnbbY1zFvBHcyIslMTSmwy8=",
                            RegisterDate = "2019-05-13 08:25:00",
                            Registration = "123"
                        },
                        new
                        {
                            Id = new Guid("4d4c2560-f7f2-4bcf-83aa-f832b17ed47f"),
                            Email = "888@testObject",
                            Name = "bbbb",
                            Password = "100.fsSHTMiMs/JsNth6Hlg/Pg==.+IYtLdw9oTLyYitCcKJzlyWkmxzvSNyw27BYxJtXHq0=",
                            RegisterDate = "2019-06-13 08:25:00",
                            Registration = "234"
                        },
                        new
                        {
                            Id = new Guid("4e052f7c-8e42-42ce-b85c-32d6d59948af"),
                            Email = "999@testObject",
                            Name = "cccc",
                            Password = "100.63tHFQEtSCWgvtMYxLVfRw==.i42OQQG11aP4tdgto5SD5tCaxka47oBhpvfkBhetm0Q=",
                            RegisterDate = "2019-07-13 08:25:00",
                            Registration = "345"
                        },
                        new
                        {
                            Id = new Guid("bc9a9d33-a10f-4bcd-a943-b669002033d7"),
                            Email = "444@testObject",
                            Name = "dddd",
                            Password = "100.9RIgQMvr7sxKRxquUEzveA==.5rsqWQZQ4Z2YOBmfPApsB36n8qAA3hwStSEqbDzndTg=",
                            RegisterDate = "2019-09-13 08:25:00",
                            Registration = "568"
                        });
                });

            modelBuilder.Entity("Comrade.Domain.Models.SystemUserSystemPermission", b =>
                {
                    b.Property<Guid>("SystemUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("fk_uuid_system_user");

                    b.Property<Guid>("SystemPermissionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("fk_uuid_system_permission");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("pk_uuid_syus_system_user_sype_system_permission");

                    b.HasKey("SystemUserId", "SystemPermissionId")
                        .HasName("rl_syus_system_user_sype_system_permission");

                    b.HasIndex("SystemPermissionId");

                    b.ToTable("syus_system_user_sype_system_permission");

                    b.HasData(
                        new
                        {
                            SystemUserId = new Guid("6adf10d0-1b83-46f2-91eb-0c64f1c638a5"),
                            SystemPermissionId = new Guid("6adf10d0-1b83-46f2-91eb-0c64f1c638a1"),
                            Id = new Guid("2696e920-2f78-4246-9d4a-bd27fcf28f83")
                        });
                });

            modelBuilder.Entity("Comrade.Domain.Models.SystemUserSystemRole", b =>
                {
                    b.Property<Guid>("SystemUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("fk_uuid_system_user");

                    b.Property<Guid>("SystemRoleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("fk_uuid_system_role");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("pk_uuid_syus_system_user_syro_system_role");

                    b.HasKey("SystemUserId", "SystemRoleId")
                        .HasName("rl_syus_system_user_syro_system_role");

                    b.HasIndex("SystemRoleId");

                    b.ToTable("syus_system_user_syro_system_role");

                    b.HasData(
                        new
                        {
                            SystemUserId = new Guid("6adf10d0-1b83-46f2-91eb-0c64f1c638a5"),
                            SystemRoleId = new Guid("3fa85f64-5717-4562-b3fc-2c963f66afa6"),
                            Id = new Guid("445ffed0-7447-4a98-aeb1-6fd0e172dd3c")
                        },
                        new
                        {
                            SystemUserId = new Guid("4d4c2560-f7f2-4bcf-83aa-f832b17ed47f"),
                            SystemRoleId = new Guid("6adf10d0-1b83-46f2-91eb-0c64f1c638a7"),
                            Id = new Guid("45561571-ec69-4923-9677-2bd2b63847d2")
                        });
                });

            modelBuilder.Entity("Comrade.Domain.Models.SystemMenu", b =>
                {
                    b.HasOne("Comrade.Domain.Models.SystemMenu", "Menu")
                        .WithMany("Submenus")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("Comrade.Domain.Models.SystemRoleSystemPermission", b =>
                {
                    b.HasOne("Comrade.Domain.Models.SystemPermission", "SystemPermission")
                        .WithMany("SystemRolePermissions")
                        .HasForeignKey("SystemPermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Comrade.Domain.Models.SystemRole", "SystemRole")
                        .WithMany("SystemRolePermissions")
                        .HasForeignKey("SystemRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SystemPermission");

                    b.Navigation("SystemRole");
                });

            modelBuilder.Entity("Comrade.Domain.Models.SystemUserSystemPermission", b =>
                {
                    b.HasOne("Comrade.Domain.Models.SystemPermission", "SystemPermission")
                        .WithMany("SystemUserPermissions")
                        .HasForeignKey("SystemPermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Comrade.Domain.Models.SystemUser", "SystemUser")
                        .WithMany("SystemUserPermissions")
                        .HasForeignKey("SystemUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SystemPermission");

                    b.Navigation("SystemUser");
                });

            modelBuilder.Entity("Comrade.Domain.Models.SystemUserSystemRole", b =>
                {
                    b.HasOne("Comrade.Domain.Models.SystemRole", "SystemRole")
                        .WithMany("SystemUserRoles")
                        .HasForeignKey("SystemRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Comrade.Domain.Models.SystemUser", "SystemUser")
                        .WithMany("SystemUserRoles")
                        .HasForeignKey("SystemUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SystemRole");

                    b.Navigation("SystemUser");
                });

            modelBuilder.Entity("Comrade.Domain.Models.SystemMenu", b =>
                {
                    b.Navigation("Submenus");
                });

            modelBuilder.Entity("Comrade.Domain.Models.SystemPermission", b =>
                {
                    b.Navigation("SystemRolePermissions");

                    b.Navigation("SystemUserPermissions");
                });

            modelBuilder.Entity("Comrade.Domain.Models.SystemRole", b =>
                {
                    b.Navigation("SystemRolePermissions");

                    b.Navigation("SystemUserRoles");
                });

            modelBuilder.Entity("Comrade.Domain.Models.SystemUser", b =>
                {
                    b.Navigation("SystemUserPermissions");

                    b.Navigation("SystemUserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
